In [16]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Titanic.csv')
df.head()

,Name,PClass,Age,Sex,Survived
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0
4,"Allison, Master Hudson Trevor",1st,0.92,male,1

In [3]:
df.isnull().sum()

Name          0
PClass        1
Age         557
Sex           0
Survived      0
dtype: int64

In [4]:
df['PClass'] = df['PClass'].fillna(df['PClass'].mode()[0])
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [5]:
df.isnull().sum()

Name        0
PClass      0
Age         0
Sex         0
Survived    0
dtype: int64

In [6]:
df.describe()

               Age     Survived
count  1313.000000  1313.000000
mean     30.397989     0.342727
std      10.816758     0.474802
min       0.170000     0.000000
25%      26.000000     0.000000
50%      30.397989     0.000000
75%      30.397989     1.000000
max      71.000000     1.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1313 non-null   object
 1   PClass      1313 non-null   object
 2   Age         1313 non-null   int64
 3   Survived    1313 non-null   int64
 4   Sex_female  1313 non-null   int64
 5   Sex_male    1313 non-null   int64
dtypes: int64(4), object(2)
memory usage: 61.7+ KB

In [8]:
df.shape

(1313, 5)

In [9]:
df.size

6565

In [10]:
df.dtypes

Name         object
PClass       object
Age         float64
Sex          object
Survived      int64
dtype: object

In [11]:
df['Age'] = df['Age'].astype(int)

In [12]:
df.dtypes

Name        object
PClass      object
Age          int64
Sex         object
Survived     int64
dtype: object

In [13]:
df = pd.get_dummies(df, columns = ['Sex'], dtype = int)

In [14]:
df.head()

,Name,PClass,Age,Survived,Sex_female,Sex_male
0,"Allen, Miss Elisabeth Walton",1st,29,1,1,0
1,"Allison, Miss Helen Loraine",1st,2,0,1,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30,0,0,1
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25,0,1,0
4,"Allison, Master Hudson Trevor",1st,0,1,0,1